apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "customersui.name" . }}
  labels:
    {{- include "customersui.labels" . | nindent 4 }}
    router: internal
spec:
  {{- if .host }}
  host: {{ .host }}
  {{- end }}
  {{- if .path }}
  path: {{ .path }}
  {{- end }}
  port:
    targetPort: 80
  to:
    kind: Service
    name: {{ include "customersui.name" . }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None