---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    {{- include "customersdb.labels" . | nindent 4 }}  
    app.kubernetes.io/name: {{ include "customers.name" . }}
  name: openjdk-17
spec:
  dockerImageRepository: {{ .Values.build.openjdk17.builderImage }}
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-uri: git@github.com:snoussi/customers-service.git
    app.quarkus.io/quarkus-version: 3.15.4.redhat-00001
    app.quarkus.io/commit-id: e8a6f4946d8ff81cd7edf6beb91c1b9893c3f8b1
    app.quarkus.io/vcs-uri: https://github.com/snoussi/customers-service.git
    app.quarkus.io/build-timestamp: 2025-04-14 - 10:10:56 +0000
  labels:
    {{- include "customersdb.labels" . | nindent 4 }}  
    app.kubernetes.io/name: {{ include "customers.name" . }}
    app.kubernetes.io/managed-by: quarkus
  name: {{ include "customers.name" . }}
spec:
  lookupPolicy:
    local: true
