kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "customersdb.name" . }}
  labels:
    {{- include "customersdb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistence.capacity }}    
  storageClassName: lvms-vg1 # delete this !!

     