kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "customers-db.name" . }}
  labels:
    {{- include "customers-db.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.persistence.capacity }}