kind: Secret
apiVersion: v1
metadata:
  name: {{ include "customersdb.name" . }}
  labels:
    {{- include "customersdb.labels" . | nindent 4 }}
data:
  database-user: {{ .Values.db.pgsql.user | b64enc }}
  database-password: {{ .Values.db.pgsql.password | b64enc }}
  database-name: {{ .Values.db.pgsql.database | b64enc}}
  database-admin-password: {{ include "customersdb.admin-password" . }}
type: Opaque