apiVersion: v1
kind: Service
metadata:
  name: {{ include "customersdb.name" . }}
  labels:
    {{- include "customersdb.labels" . | nindent 4 }}
spec:
  ports:
    - name: {{ .Values.db.service.portName }}
      protocol: TCP
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.containerPort }}
  selector:
    {{- include "customersdb.selectorLabels" . | nindent 4 }}