{{- if .Values.db.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "customersdb.serviceAccountName" . }}
  labels:
    {{- include "customersdb.labels" . | nindent 4 }}
{{- end }}
